name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Create environment file
        run: echo "OPENAI_API_KEY=sk-123" > .secrets/.env

      - name: Build
        run: go build

      - name: Test
        run: go test -race ./...